### ISSUE TITLE
Getting irradiance value for a specific segment

### ISSUE THREAD

**Issue by l4h4rl** [SunPower/pvfactors#103]
Hi @anomam ,

Thanks for developing a great package to model backside irradiance.

I am trying to implement pvfactors in my research on modelling agrivoltaics technology. Essentially, the goal is to install PV panels on top of a farm and observe the effect of shading on crop growth.

For my modelling, I am interested in getting the irradiance values for a specific segment which will be the row of crops. I know how to get the shadow and illuminated elements from ts_ground and calling .coords for coordinates and get_param_weighted('qinc') for the irradiance values. 

However, .coords returns segment that is dynamic and moves at every timestep, so I need to add an extra step to check if the shadow or illuminated elements are at the particular coordinates of interest (the row of crops). 

I am wondering if there is an easier way to get the irradiance values for specific coordinates in all of the timesteps? Sorry if this is actually explained in the documentation, I am quite new to coding and using python so I am having difficulties in reading the API part and understanding the overall backend process.

**Comment by anomam** [comment]
Hi @l4h4rl ,

Thanks a lot for your message and for using pvfactors !
Although I did hear a few years ago about such research being conducted at places like UC Davis, I never realized that pvfactors would be used for this, and such feature has therefore not been incorporated, yet.

I think what you need is being able to specify several "segments" on the ground, just like it's being done for PV rows right now. It is currently not possible to do that in pvfactors, but I think that using some of the same ideas and implementations as what's done for pv rows would help us get there. Unfortunately I think it would require some substantial amount of time to do it and I'm currently spread quite thin... I would welcome any PR to work on this though.

In the meantime, I think that there might be a workaround for this. You could return all the ground timeseries surfaces in a report as follows:
```
def fn_report(pvarray): return pvarray.ts_ground.all_ts_surfaces
```
Then you could find all the surfaces whose geometries intersect with the segment coordinates you're interested with, and do an average of the ``qinc`` (or ``qabs``) that all these surfaces calculated, weighted by how much they intersected with your fixed segment, and for all timestamps.

You'd need to pay attention to the fact that many of these surfaces will probably have a ``length`` of zero for certain timestamps, and that's because of pvfactors convention to create **all possible** shaded and illuminated surfaces that can occur in an array, even though some of them never do.

**Comment by anomam** [comment]
@l4h4rl I hope my answer above was helpful.
I'm closing this issue because it's been inactive for 2 weeks but feel free to reopen it if you have additional questions.
