### ISSUE TITLE
Update pvlib dependency to v0.8.0

### ISSUE THREAD

**Issue by anomam** [SunPower/pvfactors#114]
pvlib-python v0.8.0 has breaking API changes that will require a code update in pvfactors.

**Comment by kanderso-nrel** [comment]
Hi @anomam -- just curious, when working towards using pvlib 0.8.0 (or future versions), how much do you care about continuing to support the older pvlib versions?  For example would it be acceptable to bump the requirement to `pvlib>=0.8.0` (at least for the lower bound, maybe you'd want `<0.9.0` as well), or would you want to continue supporting the `0.6` and `0.7` series?

**Comment by anomam** [comment]
Hi @kanderso-nrel , thanks a lot for your follow-up question.
Until now I've done exactly what you're describing in your first point because it's been the easiest; I just bumped the pvlib version (so here it would be `pvlib>=0.8.0`) then fixed where it would break in pvfactors and in the tests, and then bumped the pvfactors version as well to make a new release.
That's the plan I had for this update as well, but I'm open to talking about your 2nd option if there's a strong need for it and if it's not too hard to do.

**Comment by kanderso-nrel** [comment]
Got it, thanks for the info.  I think requiring recent pvlib versions for maintenance convenience is reasonable for two reasons: pvlib is still "pre-1.0", and if nobody complains about older versions not being supported then it's no issue anyway!  Maybe once pvlib's API hits a stable release it would make sense to follow the [NEP-29 convention](https://numpy.org/neps/nep-0029-deprecation_policy.html) of all minor releases from the last two years, but that's probably a ways off still.

If you're amenable to it, I might open a PR adding support for pvlib 0.8.x, although because I'm not really familiar with the pvfactors codebase I can't promise it'll be ready any time soon, so don't let it dissuade you or someone else from getting to it first :)

**Comment by anomam** [comment]
Thanks you @kanderso-nrel, I really appreciate your inputs. It's the first time I hear about the NEP-29 convention, that's interesting stuff! I'll take a look at your PR today
