### ISSUE TITLE
Getting odd jumps in incident light from 179 degrees panel azimuth to 180 degrees

### ISSUE THREAD

**Issue by MikeJohnsonCER** [SunPower/pvfactors#118]
Hi all. 

I'm getting weird jumps in irradiances when going from a surface azimuth of 179 degrees to 180 degrees. I can see this in two-row arrays, three-row arrays, and four-row arrays (though it's less pronounced with more rows). I can find it in the front and back irradiances.

I found this when looping the same TMY weather file through pvfactors, but using azimuths of 90 to 270 degrees in 1-degree increments (experimenting with using pvfactors to find optimal orientations for solar panels in different parts of Canada). Otherwise, I hold everything else constant.

![image](https://user-images.githubusercontent.com/85246178/120528716-0074cf80-c399-11eb-94fe-e70a3e58a7f6.png)

Steps:
 
1) I set up a basic pvarray
2) I use the same TMY file for ghi, dni, and dhi, and time steps
3) I apply pvlib’s solpos to the TMY’s times and dates to determine solar positions
4) I pass all these into pvfactors’s engine.fit function while iterating the surface azimuth from 90 degrees to 270 degrees. I use a constant surface tilt.
5) I sum the irradiance for each column (e.g., qinc_back_0) to get total, annual irradiance
6) Result: I get weird irradiance bumps (up and down) around 180 degrees (this doesn't happen when I change tilts from 0 to 90 degrees in 1-degree increments).

Thoughts?
[Azimuth testing code.txt](https://github.com/SunPower/pvfactors/files/6586537/Azimuth.testing.code.txt)

[468653_59.53_-111.46_tmy.txt](https://github.com/SunPower/pvfactors/files/6586306/468653_59.53_-111.46_tmy.txt)
*** Note *** the TMY txt file needs to be converted to CSV (GitHub wouldn't let me upload a CSV for some reason)

[incident light by azimuth - 2 rows.xlsx](https://github.com/SunPower/pvfactors/files/6586540/incident.light.by.azimuth.-.2.rows.xlsx)

*edited to fix something, though still get those jumps*

**Comment by anomam** [comment]
hey @MikeJohnsonCER thanks for using pvfactors and for posting your issue here!

I think I'm starting to understand a bit what you're trying to achieve and what the problem might be.

Looking at your graph, it looks like PV rows with index 0 and 1 are swapped when the azimuth angle crosses 180 deg. 
I haven't implemented any checks for that in the code (and I should), but a hard requirement for the calculation to be physically correct is that the "axis_azimuth" direction used in the array parameters dict and the "surface_azimuth" inputs to the engine should be **orthogonal**, just like on single-axis trackers for instance where you could imagine an axis azimuth = 0 deg (North direction of the torque tube / rotation axis) for trackers rotating from East (surface azimuth = 90 deg, rotation angles < 0) to West (surface azimuth = 270 deg, rotation angles > 0). I tried to explain this [here](https://sunpower.github.io/pvfactors/concepts/index.html#pv-array-parameters) but I think a check in the code is needed.

So if you're trying to do an optimisation on PV array azimuth angles, I think you should update both "axis_azimuth" in the array parameters, and "surface_azimuth" in the engine inputs, so that they're consistent (orthogonal).

Please let me know if I understood the issue correctly, and if my suggestion is helping!

**Comment by MikeJohnsonCER** [comment]
Yup. Solved it. Thanks. :)

**Comment by anomam** [comment]
Great, I'll close this issue then but feel free to re-open it if you still have questions!
