### ISSUE TITLE
back irradiance

### ISSUE THREAD

**Issue by tcapelle** [SunPower/pvfactors#59]
I am comparing the model with data from our installation and I am always overestimating back irradiance, mostly on winter.
I am comparing `qinc` from the `back` of the `pvrow` to my reference cell data. Should I also consider `reflection` and `iso`?
![back_irradiance_compare](https://user-images.githubusercontent.com/18441985/61387467-7ca1bf00-a8b6-11e9-9787-e1d3667bc813.png)
I took the back irradiance from the surface element equivalent to the reference cell position.

**Comment by anomam** [comment]
Hi @tcapelle , thanks a lot for reaching out!

``qinc`` is actually the sum of all the light components calculated in pvfactors (direct, isotropic, circumsolar, horizon, and reflection), so this is the right output to use: it's the calculated total irradiance incident on the back surface.

We have a paper that we presented at IEEE PVSC 46 coming up soon that show a validation and benchmark of pvfactors. Some important points to consider are the following:
* edge effects: pvfactors (and other simple 2D view factor models) assume infinitely long PV rows, so this means that if you carry out measurements on a small PV system, the edge effects (ie the light coming from the sides of the PV systems) will have a lot of impact and pvfactors results will make less sense, and will very likely be lower. Since pvfactors is over-predicting here, this is probably not the issue.
* racking: we also compared pvfactors predictions to measurements performed on a fixed tilt system that had a heavy racking system, with large concrete blocks on the ground. For that particular system, we saw that the racking system had a large effect on back-surface irradiance measurements, and we observed big discrepancies between measurements and calculated values especially during the winter, and less during the summer, most likely because the concrete footings cast long shadows on the ground during the winter, therefore decreasing the observed back-side irradiance on the systems. And simple 2D VF models like pvfactors are generally not accounting for complex racking systems like that, and so they can perform poorly. This could be what's happening in your case.
* AOI losses: another point is that pvfactors doesn't apply any angle-of-incidence (AOI) losses to the calculated irradiance, so in general, pvfactors calculations will be closer to measurements performed with pyranometers (vs. ref cells) because these sensors are less sensitive to AOI effects. So this could contribute to higher calculated back-side irradiance.

Quick question: why is there such a drop in measured irradiance at the beginning of September 2017? (which doesn't seem to recover anytime onward) Does this happen on the front surface as well?

**Comment by tcapelle** [comment]
Thanks you for the detailed explanation.
My front irradiances are almost perfect:
![front_irradiance_compare](https://user-images.githubusercontent.com/18441985/61464953-74f61f00-a977-11e9-8c0a-5ad3813b94ac.png)

**Comment by anomam** [comment]
Hi @tcapelle , this kind of capability doesn't exist in pvfactors at this moment (nor does it in bifacialvf or PVSyst as far as I know), but I don't think it would be impossible to implement, just difficult.
For more detailed simulations like that, people generally turn to 3D ray-tracing methods: [bifacial_radiance](https://github.com/NREL/bifacial_radiance) is an open-source package that would allow you to do this. There is a bit of a learning curve, but I'm sure the maintainers would be happy to help!

**Comment by tcapelle** [comment]
I am already using bifacial_radiance.
It is far from being easy.

**Comment by anomam** [comment]
Thanks for the awesome feedback @tcapelle ! We've been putting a lot of effort into it and I really appreciate your contribution too.
I'm going to close this issue for now since it's been a while, but feel free to re-open it if you have additional questions.
