### ISSUE TITLE
Get front surface irradiances in fastmode

### ISSUE THREAD

**Issue by tcapelle** [SunPower/pvfactors#81]
Hey @anomam,
I am trying to compute irradiances using fast mode (pretty cool btw) and want to be able to recover front irradiances as well that back.
I defined a function as shown in the examples:
```
def fn_report(pvarray, bf_factor=0.7): 
    return {'front': (pvarray.ts_pvrows[fast_mode_pvrow_index].front.get_param_weighted('qinc')),
            'back':  (bf_factor*pvarray.ts_pvrows[fast_mode_pvrow_index].back.get_param_weighted('qinc'))}
```
As you can see, I am trying to compute a "weighted" irradiance, but I am unable to recover a front surface irradiance. I get `KeyError: 'qinc'` for front surface.
Any tips on how to inspect this type of elements to see available quantities, params?

**Comment by tcapelle** [comment]
Reading the code, It looks like front irradiances are never computed on fast mode.

**Comment by anomam** [comment]
Hi @tcapelle , I apologize that this is not very clear in the documentation yet, I'm not very satisfied with how the doc looks like these days, especially after all the new features implemented. I hope to work on it soon, but we do happily take contributions if you ever feel like it!
You're very right, the fast mode doesn't "really" calculate front side irradiance using the view factors, but [it does use the Perez model](https://sunpower.github.io/pvfactors/theory/problem_formulation.html#fast-simulations) values as a proxy. The way I would probably do it in your code is using the ``'total_perez'`` values calculated in [the irradiance model](https://sunpower.github.io/pvfactors/_modules/models.html#HybridPerezOrdered) using pvlib.
```
def fn_report(pvarray, bf_factor=0.7): 
    return {'front': (pvarray.ts_pvrows[fast_mode_pvrow_index].front.get_param_weighted('total_perez')),
            'back':  (bf_factor*pvarray.ts_pvrows[fast_mode_pvrow_index].back.get_param_weighted('qinc'))}
```
Let me know if it works on your end and if you have any questions!

**Comment by tcapelle** [comment]
I will try, but something like this is wthat I was looking for.

**Comment by anomam** [comment]
Hi @tcapelle , I'm closing this issue since it sounded like my suggestion helped. Feel free to re-open if needed!
Btw, I just finished implementing a lot of updates for the full mode, and it should now run 8760 simulations in a couple of seconds now (no parallel workers needed), and it still calculates irradiance with view factors and reflections for all the surfaces at the same time. And now, your initial report function (below) should also work when using the full mode:
```
def fn_report(pvarray, bf_factor=0.7): 
    return {'front': (pvarray.ts_pvrows[fast_mode_pvrow_index].front.get_param_weighted('qinc')),
            'back':  (bf_factor*pvarray.ts_pvrows[fast_mode_pvrow_index].back.get_param_weighted('qinc'))}
```
I still need to update the docs and make a new release, but you can use the current master branch if you want to try it in advance. Let me know if you have any questions or remarks!
